Repository jb087/remisystem, pull requests merged in 2020-05, with the labels that each got.

#3 Implement basic views, add Prettier, add React Router
  .prettierrc
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/components/HomePanel.js
  src/components/Login.js
  src/components/NavigationBar.js
  src/components/NewReminder.js
  src/components/Panel.js
  src/components/Register.js
  src/components/ReminderPanel.js
  src/components/ReminderTile.js
  src/components/SettingsPanel.js
  src/components/Tiles.js
  src/components/css/NavigationBar.css
  src/components/css/ReminderPanel.css
  src/components/css/ReminderTile.css
  src/components/css/Tiles.css
  src/logo-small.png
  src/logo-with-bg.png
  src/logo.png
Labels: enhancement

#7 Basic view - the same as #3 PR but with master branch as base
  .prettierrc
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/components/HomePanel.js
  src/components/Login.js
  src/components/NavigationBar.js
  src/components/NewReminder.js
  src/components/Panel.js
  src/components/Register.js
  src/components/ReminderPanel.js
  src/components/ReminderTile.js
  src/components/SettingsPanel.js
  src/components/Tiles.js
  src/components/css/NavigationBar.css
  src/components/css/ReminderPanel.css
  src/components/css/ReminderTile.css
  src/components/css/Tiles.css
  src/logo-small.png
  src/logo-with-bg.png
  src/logo.png
Labels: duplicate, enhancement

#6 Firebase Authentication
  package-lock.json
  package.json
  src/App.js
  src/components/ButtonWithSpinner.js
  src/components/Home.js
  src/components/HomePanel.js
  src/components/Login.js
  src/components/NavigationBar.js
  src/components/Panel.js
  src/components/PanelUnlogged.js
  src/components/PasswordReset.js
  src/components/Register.js
  src/components/Reminder.js
  src/components/ReminderPanel.js
  src/components/Settings.js
  src/components/SettingsEmail.js
  src/components/SettingsPanel.js
  src/components/SettingsPassword.js
  src/components/SettingsReminder.js
  src/components/SignIn.js
  src/components/SignUp.js
  src/components/Tiles.js
  src/firebase.js
  src/hooks/useForm.js
  src/providers/UserProvider.js
Labels: enhancement

#10 Api
  api/db/remisystem.sqlite
  api/routes/api.js
  api/service/mailService.js
  api/service/noteService.js
Labels: enhancement

#8 Implement note's edit page
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/ButtonWithSpinner.js
  src/components/LoadingSpinner.js
  src/components/NewNote.js
  src/components/NewReminder.js
  src/components/Note.js
  src/components/NoteCard.js
  src/components/NoteForm.js
  src/components/NoteTile.js
  src/components/Reminder.js
  src/components/ReminderModal.js
  src/components/ReminderModalBackdrop.js
  src/components/ReminderTile.js
  src/components/Reminders.js
  src/components/Tiles.js
  src/components/css/NavigationBar.css
  src/components/css/NoteTile.css
  src/components/css/Reminder.css
  src/components/css/ReminderPanel.css
  src/components/css/Reminders.css
  src/hooks/useReminders.js
Labels: enhancement

#11 Implement note's edit page (copy of #8 PR)
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/ButtonWithSpinner.js
  src/components/LoadingSpinner.js
  src/components/NewNote.js
  src/components/NewReminder.js
  src/components/Note.js
  src/components/NoteCard.js
  src/components/NoteForm.js
  src/components/NoteTile.js
  src/components/Reminder.js
  src/components/ReminderModal.js
  src/components/ReminderModalBackdrop.js
  src/components/ReminderTile.js
  src/components/Reminders.js
  src/components/Tiles.js
  src/components/css/NavigationBar.css
  src/components/css/NoteTile.css
  src/components/css/Reminder.css
  src/components/css/ReminderPanel.css
  src/components/css/Reminders.css
  src/hooks/useReminders.js
Labels: enhancement

#9 Connect fronted with backend
  api/db/remisystem.sqlite
  api/routes/api.js
  api/service/noteService.js
  src/components/Home.js
  src/components/NewNote.js
  src/components/Note.js
  src/hooks/useToken.js
  src/services/noteService.js
  src/services/reminderService.js
  src/utils/requestUtils.js
Labels: enhancement

#12 Fix protruding title in tile in Home screen
  api/db/remisystem.sqlite
  src/components/css/NoteTile.css
Labels: bug

#13 Fix: send milliseconds to backend
  api/db/remisystem.sqlite
  src/components/Note.js
  src/services/noteService.js
  src/services/reminderService.js
Labels: bug
